version: '3'
services:
  app:
    build:
      context: .
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./:/opt/app
    working_dir: /opt/app/src
    ports:
      - 8050:8050
    command: bash -c "python app.py"
